// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.loadTasks('tasks');
    return grunt.initConfig({
      'ember-s3': {
        files: {
          src: 'dist/*.js'
        }
      }
    });
  };

}).call(this);
